GET http://localhost/api/EpisodeDownloads HTTP/1.1

###

GET http://localhost/api/EpisodeDownloads/2022-02-26/podcast/2/episode/4 HTTP/1.1

# Content-Type: application/json
# {
#    "day":"2020-03-09",
#    "episodeId":4,
#    "podcastId":4
# }
###